import { createHash } from 'node:crypto';
import { serializeLibrary } from './helpers.js';
import type { SyncedLibrary } from './types.js';

// updatedAt is regenerated by the legacy deserializer. Compare persisted content,
// not wall clocks, so two reads of the same library have the same revision.
export const libraryRevision = (library: SyncedLibrary) =>
  createHash('sha256').update(serializeLibrary(library)).digest('hex');
